### ISSUE TITLE
pandas is missing from the requirement.txt

### ISSUE THREAD

**Issue by wckdouglas** [betsig/how_are_we_stranded_here#4]
Hi @betsig, 

Thanks for implementing this great idea! Upon running the tool, I was told ```pandas``` was missing, which is not a requirement in RSeQC (I checked setup.py only). It is probably better to include ```pandas``` in the requirements.txt file. Thanks again for the tool!

**Comment by betsig** [comment]
I added numpy and pandas as requirements here https://github.com/betsig/how_are_we_stranded_here/commit/626c1ab303a68e294e2ad9d2cdd15a483814f21d. Hopefully that helps with installing it :)
